#!/bin/bash

export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
export PASS=$(sed -n '3p' /tmp/.auth)

echo "***Login to Docker Hub***"
docker login -u raiyan -p $PASS

echo "****Running Docker App****"
docker-compose up -d
